用于numpy的学习

In [1]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(b)

<class 'numpy.ndarray'>
(3,)
1 2 3
[1 2 3]
(2, 3)
[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np

a = np.zeros((2, 3))
print(a)

b = np.ones((2, 3))
print(b)

c = np.full((2, 3), 7)
print(c)

d = np.eye(3)
print(d)

e = np.random.random((2, 3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.97368848 0.30133106 0.60406781]
 [0.16866492 0.61487097 0.73983341]]


In [10]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

b = a[:2, 2:]
print(b)

print(a[1, 2])
b[1, 0] = 100
print(a[1, 2])
b[1, 0] = 7

r1 = a[1, :]
r2 = a[1:2, :]
print(r1, r1.shape)
print(r2, r2.shape)

c1 = a[:, 2]
c2 = a[:, 2:3]
print(c1, c1.shape)
print(c2, c2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]
7
100
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 3  7 11] (3,)
[[ 3]
 [ 7]
 [11]] (3, 1)


In [7]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)
b = np.array([0, 2, 0, 1])
print(a[np.array(range(4)), b])
a[np.array(range(4)), b] += 100
print(a)

bool_idx = a > 100
print(bool_idx)
print(a[bool_idx])
print(a[a > 100])

[1 4 5]
[1 4 5]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[101   2   3]
 [  4   5 106]
 [107   8   9]
 [ 10 111  12]]
[[ True False False]
 [False False  True]
 [ True False False]
 [False  True False]]
[101 106 107 111]
[101 106 107 111]


In [12]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(np.sqrt(x))

v = np.array([9, 10])
w = np.array([11, 12])
print(np.dot(v, w))
print(np.dot(x, v))
print(np.dot(v, x))
print(np.dot(x, y))

print(np.sum(x))
print(np.sum(x, axis = 0))
print(np.sum(x, axis = 1))

print(x.T)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
219
[29 67]
[39 58]
[[19 22]
 [43 50]]
10
[4 6]
[3 7]
[[1 3]
 [2 4]]


In [34]:
import numpy as np


x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

for i in range(4):
    y[i, :] = x[i, :] + v   
print(y)

vv = np.tile(v, (4, 1))
y = x + vv
print(y)

y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [40]:
import numpy as np

v = np.array([1, 2, 3])
w = np.array([4, 5])

print(np.reshape(v, (3, 1)) * w)

x = np.array([[1, 2, 3], [4, 5, 6]])
print(x + v)

print((x.T + w).T)

print(x + np.reshape(w, (2, 1)))

print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
